import React, { useEffect, useState } from 'react';
import { getPredictionHistory } from '../services/api';
import { Clock, AlertCircle, CheckCircle } from 'lucide-react';

interface HistoryRecord {
  id: number;
  patient_data: any;
  probability: number;
  risk_level: string;
  created_at: string;
}

export const History: React.FC = () => {
  const [history, setHistory] = useState<HistoryRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const data = await getPredictionHistory();
        setHistory(data);
      } catch (err) {
        setError('Failed to load patient history. Please try again later.');
      } finally {
        setLoading(false);
      }
    };
    fetchHistory();
  }, []);

  if (loading) return <div className="text-center py-20 text-gray-500">Loading patient records...</div>;

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex items-center space-x-3 mb-8">
        <div className="p-3 bg-blue-50 rounded-full text-secondary">
          <Clock size={28} />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-gray-800">Patient Assessment History</h2>
          <p className="text-sm text-gray-500">Chronological log of all risk predictions generated by your account.</p>
        </div>
      </div>

      {error && <div className="p-4 bg-red-50 text-red-600 rounded-lg">{error}</div>}

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {history.length === 0 ? (
          <div className="p-10 text-center text-gray-500">No patient history found. Run an assessment to see data here.</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-100 text-gray-600 text-sm uppercase tracking-wider">
                  <th className="p-4 font-semibold">Date & Time</th>
                  <th className="p-4 font-semibold">Key Vitals (Gluc / BMI / Age)</th>
                  <th className="p-4 font-semibold">Probability</th>
                  <th className="p-4 font-semibold">Risk Level</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {history.map((record) => {
                  const date = new Date(record.created_at).toLocaleDateString('en-US', {
                    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
                  });
                  const isHigh = record.risk_level === 'High';
                  const isMed = record.risk_level === 'Medium';
                  const Icon = isHigh || isMed ? AlertCircle : CheckCircle;
                  const colorClass = isHigh ? 'text-red-600 bg-red-50' : isMed ? 'text-yellow-600 bg-yellow-50' : 'text-green-600 bg-green-50';

                  return (
                    <tr key={record.id} className="hover:bg-gray-50 transition-colors">
                      <td className="p-4 text-sm text-gray-700 whitespace-nowrap">{date}</td>
                      <td className="p-4 text-sm text-gray-600">
                        Gluc: <span className="font-medium">{record.patient_data.Glucose}</span> | 
                        BMI: <span className="font-medium">{record.patient_data.BMI}</span> | 
                        Age: <span className="font-medium">{record.patient_data.Age}</span>
                      </td>
                      <td className="p-4 text-sm font-semibold text-gray-800">
                        {(record.probability * 100).toFixed(1)}%
                      </td>
                      <td className="p-4">
                        <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium ${colorClass}`}>
                          <Icon size={12} className="mr-1" /> {record.risk_level}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};